name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm build

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: ${{ secrets.INFISICAL_MACHINE_IDENTITY_ID }}
          domain: ${{ secrets.INFISICAL_API_URL }}
          project-slug: ${{ secrets.INFISICAL_PROJECT_SLUG }}
          env-slug: "ci-staging"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run deploy:staging

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: ${{ secrets.INFISICAL_MACHINE_IDENTITY_ID }}
          domain: ${{ secrets.INFISICAL_API_URL }}
          project-slug: ${{ secrets.INFISICAL_PROJECT_SLUG }}
          env-slug: "ci-prod"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run deploy:prod
